version: "3.9"

services:
  people-counter:
    build: .
    container_name: people-counter
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./models:/app/models
      - /tmp/people:/tmp/people
