[project]
name = "people-counter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.0",
    "opencv-python>=4.13.0.90",
    "python-multipart>=0.0.21",
    "ultralytics>=8.4.6",
    "uvicorn>=0.40.0",
]
